### ISSUE TITLE
Bottom sockets sometimes do not connect

### ISSUE THREAD

**Issue by briantkho** [function-junctions/function-junctions#4]
Occasionally when attempting to connect the bottom nodes, the socket refuses connection. May have something to do with the Tarjan algorithm

https://github.com/function-junctions/function-junctions/assets/86168500/1152b759-43bf-4533-a890-2ecc72e09730

**Comment by AydanGaite** [comment]
This is an issue relating to our previous repo. No need to look at this anymore
