### ISSUE TITLE
Outdated documentation link

### ISSUE THREAD

**Issue by itsdombo** [function-junctions/function-junctions#84]
**Describe the bug**
Documentation link in README.md is outdated

![image](https://github.com/function-junctions/function-junctions/assets/31048418/f5b614ad-cb89-4571-b67a-13f459e07bc5)

**Comment by AydanGaite** [comment]
Updated. Thanks for chiming in!

**Comment by AydanGaite** [comment]
https://stellar-acrylic-da8.notion.site/0c4b503abdf34d9cbf3b14a9b6869aa3?v=7f7204735ea046319417b01638e23fe4
